export const IMAGES = {
    home_bar_selected: require("../../assets/home_active.png"),
    home_bar: require('../../assets/home_inactive.png'),
    chat_bar_selected: require("../../assets/chat_active.png"),
    chat_bar: require('../../assets/chat_inactive.png'),
    calendar_bar_selected: require("../../assets/calendar_active.png"),
    calendar_bar: require('../../assets/calendar_inactive.png'),
    news_bar_selected: require("../../assets/news_active.png"),
    news_bar: require('../../assets/news_inactive.png'),
    profile_bar_selected: require("../../assets/profile_active.png"),
    profile_bar: require('../../assets/profile_inactive.png'),
    notification_icon:require('../../assets/notification_active.png'),
    menu_icon:require("../../assets/menu_icon.png"),
    down_arrow:require("../../assets/down_arrow.png"),
    up_arrow:require('../../assets/up_arrow.png'),
    money_icon:require("../../assets/money_icon.png"),
    profile_icon:require("../../assets/profile_icon.png"),
    wave_icon:require("../../assets/wave_icon.png"),
    checkmark:require("../../assets/checkmark.png"),
    round_arrow:require("../../assets/round_arrow.png"),
    flag_icon:require("../../assets/flag.png")
}